name: kadai4_test
on: [push]
jobs:
  io_test:
    name: Use Linux commands
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      run: chmod +x gcd.sh test_gcd.sh
      run: ./test_gcd.sh
